FROM pritunl/archlinux:latest

# Dependencies
RUN pacman -Sy && pacman -S --noconfirm texlive-most minted pygmentize

# Fonts
RUN pacman -S --noconfirm wget unzip make
RUN mkdir ~/.fonts && \
    wget --no-check-certificate https://www.fontsquirrel.com/fonts/download/fira-sans && \
    unzip -o -d ~/.fonts/ fira-sans && \
    wget --no-check-certificate https://www.fontsquirrel.com/fonts/download/fira-mono && \
    unzip -o -d ~/.fonts/ fira-mono

WORKDIR /source
COPY . /source
RUN make
